Replaced logic to bind to all addresses on 0.0.0.0
bk138/droidVNC-NG pull request #15
Opened 2021-04-21 09:42 UTC by amroessam

2021-04-21 09:42 UTC, amroessam commented
https://github.com/bk138/droidVNC-NG/issues/14

2021-05-05 19:43 UTC, bk138 requested changes

2021-05-05 19:43 UTC, bk138 commented on .idea/compiler.xml
> +    <bytecodeTargetLevel target="11" />
Please don't change this file as it's not related.

2021-05-05 19:43 UTC, bk138 commented on .idea/gradle.xml
> +        <option name="delegatedBuild" value="true" />
Please don't change this file as it's not related.

2021-05-05 19:43 UTC, bk138 commented on .idea/misc.xml
> +  <component name="ProjectRootManager" version="2" languageLevel="JDK_11" default="true" project-jdk-name="11" project-jdk-type="JavaSDK">
Please don't change this file as it's not related.

2021-05-05 19:43 UTC, bk138 commented on app/src/main/java/net/christianbeier/droidvnc_ng/MainService.java
> -            //unused
please don't change unrelated lines

2021-05-05 19:43 UTC, bk138 commented on app/src/main/java/net/christianbeier/droidvnc_ng/MainService.java
> +        return "0.0.0.0:" + port;
In fact, this is the only change needed for this pull request.

2021-05-11 18:54 UTC, closed without merging