Refactor MainService to prevent unnecessary activity starts
bk138/droidVNC-NG pull request #243
Opened 2024-10-18 12:02 UTC by Niels-Be

I was about to automate the session startup with my DPC application.
My device is in Lock Task Mode, so starting activities is prohibited.
This cleans up the startup process in case all permissions are granted, that no activities has to be launched.

There should be no logic change. Just moving the code in separate methods
and directly check the permission condition in the service before starting the activity to request it.

Most of the time this will safe the overhead of jumping between activities and service
as permissions are only requested the first time.
This helps when automating the start process of a session.

Also send a response to the caller in some failure cases.

2024-10-18 13:36 UTC, bk138 requested changes
Please remove the unrelated whitespace changes, it makes review way harder than need be. Thanks! :-)

2024-10-18 13:36 UTC, bk138 commented on app/src/main/java/net/christianbeier/droidvnc_ng/MainService.java
> -    private static final String PREFS_KEY_SERVER_LAST_PORT = "server_last_port" ;
please don't edit unrelated whitespace, it makes review harder :-)

2024-10-18 13:36 UTC, bk138 commented on app/src/main/java/net/christianbeier/droidvnc_ng/MainService.java
> -        mWakeLock = ((PowerManager) instance.getSystemService(Context.POWER_SERVICE)).newWakeLock((PowerManager.SCREEN_DIM_WAKE_LOCK| PowerManager.ACQUIRE_CAUSES_WAKEUP | PowerManager.ON_AFTER_RELEAS
here too?

2024-10-18 16:19 UTC, Niels-Be commented
@bk138 sorry about that. There is an option hide those in the UI but I pushed again without those.

2025-05-08 15:42 UTC, Niels-Be commented
Rebased onto master

2025-08-10 20:38 UTC, closed without merging