added UVNC Repeater support
bk138/droidVNC-NG pull request #77
Opened 2022-04-25 15:37 UTC by anreis75

When applied, this commit will allow to create a UVNC repeater connection MODE 2 (https://uvnc.com/products/uvnc-repeater.html). Entering a -1 in the port field allows us to start the VNC server without accepting incoming connections, while being able to create outgoing connections
-

2022-04-26 10:24 UTC, anreis75 commented on app/src/main/cpp/droidvnc-ng.c
> +repeaterConnection(rfbScreenInfoPtr rfbScreen,
Yes, it is like the reverse connection. I took the solution from libvncserver\examples\repeater.c. And yes, you can add this to libvncserver

2022-04-26 10:37 UTC, anreis75 commented on app/src/main/res/layout/activity_main.xml
> +        <Button
I think it's not possible. There's no way to find out who's on the other side. In the repeater MODE a Server and a Viewer both send the ID immediately after the connection is established and the repeater pairs the viewer and the server  having the same ID (and cuts ID out of the data streams).

2022-04-26 10:51 UTC, anreis75 commented on app/src/main/cpp/droidvnc-ng.c
> +    if (port != -1) {
Of course, but in my opinion it is better to give the user the opportunity to choose whether he needs a listening mode or not. Those who use a reverse ор а repeater connection would most likely start the VNC server without listening to improve security..

2022-04-26 10:54 UTC, anreis75 commented on app/src/main/res/values/strings.xml
> +    <string name="main_activity_no_listening">The server is not accepting incoming connections</string>
By entering -1 as the server port, the server runs without listening and therefore cannot accept incoming connections, but can establish a reverse or repeater connection

2022-04-26 10:56 UTC, anreis75 commented on app/src/main/cpp/droidvnc-ng.c
> +static void clientGone(rfbClientPtr cl)
yes

2022-04-26 11:22 UTC, anreis75 commented on app/src/main/res/values/strings.xml
> +    <string name="main_activity_no_listening">The server is not accepting incoming connections</string>
Perhaps it is better to redefine the text

2022-04-27 13:37 UTC, bk138 commented on app/src/main/res/layout/activity_main.xml
> +        <Button
OK.

2022-04-27 13:39 UTC, bk138 commented on app/src/main/cpp/droidvnc-ng.c
> +    if (port != -1) {
Let's leave out the disabling of listening for now. I will add it later as a separate feature. Can you adapt your PR accordingly?

2022-04-27 13:39 UTC, bk138 commented on app/src/main/res/values/strings.xml
> +    <string name="main_activity_no_listening">The server is not accepting incoming connections</string>
Same here, let's tackle disabling of listening as a separate issue.

2022-04-27 13:40 UTC, bk138 commented on app/src/main/cpp/droidvnc-ng.c
> +repeaterConnection(rfbScreenInfoPtr rfbScreen,
OK, will have a look. This can stay in the PR in the meantime.

2022-04-27 13:44 UTC, bk138 requested changes

2022-04-27 13:44 UTC, bk138 commented on app/src/main/cpp/droidvnc-ng.c
> +static void clientGone(rfbClientPtr cl)
Please remove it.

2022-04-27 13:44 UTC, bk138 commented on app/src/main/java/net/christianbeier/droidvnc_ng/MainActivity.java
> +
This should be removed from the PR as well please.

2022-04-27 13:44 UTC, bk138 commented on app/src/main/res/layout/activity_main.xml
> +                    android:inputType="numberSigned"
Please remove this change as well.

2022-04-27 15:08 UTC, anreis75 commented on app/src/main/cpp/droidvnc-ng.c
> +static void clientGone(rfbClientPtr cl)
added a commit

2022-04-27 18:57 UTC, bk138 commented
> I rolled back the changes.

Looks good on a quick look, I'll do some testing and en passant take care of https://github.com/LibVNC/libvncserver/issues/465 and https://github.com/LibVNC/libvncserver/issues/87 and then merge.

2022-04-28 18:56 UTC, merged

2022-04-28 18:57 UTC, bk138 commented
Testing succesful, merged. I'll add some minor tweaks myself. Thanks for the contribution @anreis75 ! Is this going to be used in one of the sitekiosk products?

2022-05-02 07:29 UTC, anreis75 commented
Thank you for your performance. We intend to integrate your application into our sitekiosk solution.

2022-05-02 12:31 UTC, bk138 commented
> Thank you for your performance. We intend to integrate your application into our sitekiosk solution.

Alright, go ahead and please take care to adhere to the terms of the GPL.

Talking of legal issues @anreis75 , do you want to claim the copyright of your contribution for your company? If so, I can add the corresponding entries in the headers of affected files.

Last, if your company wants/needs assistance w.r.t. droidVNC-NG integration, I'm available for consulting. In that case, feel free to email me via contact@christianbeier.net.

2022-05-03 06:52 UTC, anreis75 commented
Thank you for your help and your offer. 
Of course we adhere to the conditions of the  GPL. 
It is not necessary to add entries in the headers of files.
We still need some adjustments in the application, I will create an issue later.